services:
  - type: web
    name: smart-dispute-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: FLASK_ENV
        value: production  # use "production" for deployed app
      - key: SECRET_KEY
        value: your-production-secret  # change in Render dashboard
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name  # update with actual DB name
          property: connectionString
